"""
Phase 1 (CPU, judge-independent): extract developer co-change gold from BugsInPy.

For each bug, bug_patch.txt is the developer's actual fix diff. The set of files
touched = the developer co-change set for resolving one real issue. This is a
DEVELOPER-BEHAVIOR signal, generated by git history, ORTHOGONAL to any static
parser. We do NOT interpret it as "dependency" — it is task/change-coupling.

Red lines honored:
- full sample, no project/subset cherry-picking
- deterministic rules only (judge-independent)
- tangling de-noise reported in TWO versions (raw vs untangled), nothing hidden
- co-change != dependency: vocabulary is 'co-change edge', never 'dependency'
- everything dumped to timestamped files; no silent skips (errors logged)
"""
import os, re, json, sys, time, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
BUGS = os.path.join(ROOT, "BugsInPy", "projects")
OUT = os.path.join(ROOT, "out")
os.makedirs(OUT, exist_ok=True)
STAMP = sys.argv[1] if len(sys.argv) > 1 else time.strftime("%Y%m%d_%H%M%S")
LOG = open(os.path.join(OUT, f"p1_log_{STAMP}.txt"), "w", encoding="utf-8")

def log(*a):
    s = " ".join(str(x) for x in a)
    print(s)
    LOG.write(s + "\n"); LOG.flush()

# diff --git a/<path> b/<path>  -> capture both; renames produce differing a/b
DIFF_RE = re.compile(r"^diff --git a/(.+?) b/(.+?)\s*$", re.M)

def parse_patch_files(text):
    """Return ordered unique list of file paths touched by the patch."""
    files = []
    for m in DIFF_RE.finditer(text):
        a, b = m.group(1), m.group(2)
        for p in (a, b):
            if p not in files:
                files.append(p)
    return files

def is_test_file(p):
    pl = p.lower()
    base = os.path.basename(pl)
    return (
        "/test" in "/" + pl
        or base.startswith("test_")
        or base.endswith("_test.py")
        or "/tests/" in "/" + pl
        or base == "conftest.py"
    )

def is_py(p):
    return p.endswith(".py")

records = []
proj_dirs = sorted(d for d in os.listdir(BUGS) if os.path.isdir(os.path.join(BUGS, d)))
log(f"[start] {STAMP}  projects={len(proj_dirs)}")

for proj in proj_dirs:
    bugs_root = os.path.join(BUGS, proj, "bugs")
    if not os.path.isdir(bugs_root):
        log(f"[warn] no bugs dir for {proj}")
        continue
    info_path = os.path.join(BUGS, proj, "project.info")
    github = ""
    try:
        with open(info_path, encoding="utf-8", errors="replace") as f:
            mt = re.search(r'github_url="([^"]+)"', f.read())
            if mt: github = mt.group(1)
    except Exception as e:
        log(f"[warn] read project.info {proj}: {e!r}")
    bug_ids = sorted((b for b in os.listdir(bugs_root)
                      if os.path.isdir(os.path.join(bugs_root, b))),
                     key=lambda x: (len(x), x))
    for bid in bug_ids:
        bdir = os.path.join(bugs_root, bid)
        patch = os.path.join(bdir, "bug_patch.txt")
        info = os.path.join(bdir, "bug.info")
        rec = {"project": proj, "bug_id": bid, "github": github,
               "buggy_commit": "", "fixed_commit": "", "test_file": "",
               "patch_ok": False, "all_files": [], "py_files": [],
               "src_py_files": [], "test_py_files": [], "n_src_py": 0}
        try:
            with open(info, encoding="utf-8", errors="replace") as f:
                t = f.read()
            for k, key in [("buggy_commit_id", "buggy_commit"),
                           ("fixed_commit_id", "fixed_commit"),
                           ("test_file", "test_file")]:
                mm = re.search(k + r'="([^"]*)"', t)
                if mm: rec[key] = mm.group(1)
        except Exception as e:
            log(f"[warn] bug.info {proj}/{bid}: {e!r}")
        try:
            with open(patch, encoding="utf-8", errors="replace") as f:
                ptext = f.read()
            files = parse_patch_files(ptext)
            rec["patch_ok"] = True
            rec["all_files"] = files
            rec["py_files"] = [p for p in files if is_py(p)]
            rec["test_py_files"] = [p for p in rec["py_files"] if is_test_file(p)]
            rec["src_py_files"] = [p for p in rec["py_files"] if not is_test_file(p)]
            rec["n_src_py"] = len(rec["src_py_files"])
        except Exception as e:
            log(f"[warn] bug_patch {proj}/{bid}: {e!r}")
        records.append(rec)

# ---- aggregate (raw vs untangled) ----
def edges_from(files):
    """unordered file pairs among src py files (co-change edges)."""
    fs = sorted(set(files))
    out = []
    for i in range(len(fs)):
        for j in range(i + 1, len(fs)):
            out.append((fs[i], fs[j]))
    return out

# UNTANGLE heuristic (deterministic, reported separately, nothing hidden):
#  drop bugs whose src-py fan-out is implausibly large for a single bug fix
#  (Herzig: tangled commits bundle unrelated work). Threshold reported.
UNTANGLE_MAX_SRC = 8   # bugs touching > N source .py files flagged as likely tangled

def summarize(recs, label, untangle=False):
    multi = [r for r in recs if r["n_src_py"] >= 2]
    if untangle:
        multi = [r for r in multi if r["n_src_py"] <= UNTANGLE_MAX_SRC]
    edges = []
    for r in multi:
        for (a, b) in edges_from(r["src_py_files"]):
            edges.append({"project": r["project"], "bug_id": r["bug_id"],
                          "fixed_commit": r["fixed_commit"], "a": a, "b": b})
    s = {
        "label": label,
        "untangle_applied": untangle,
        "untangle_max_src": UNTANGLE_MAX_SRC if untangle else None,
        "n_bugs_total": len(recs),
        "n_patch_ok": sum(1 for r in recs if r["patch_ok"]),
        "n_bugs_with_src_py": sum(1 for r in recs if r["n_src_py"] >= 1),
        "n_multifile_src_bugs": len(multi),
        "n_cochange_edges": len(edges),
        "src_py_fanout_hist": {},
    }
    hist = {}
    for r in recs:
        hist[r["n_src_py"]] = hist.get(r["n_src_py"], 0) + 1
    s["src_py_fanout_hist"] = dict(sorted(hist.items()))
    # per project
    perproj = {}
    for r in recs:
        p = r["project"]
        perproj.setdefault(p, {"bugs": 0, "multifile": 0, "edges": 0})
        perproj[p]["bugs"] += 1
    for r in multi:
        perproj[r["project"]]["multifile"] += 1
        perproj[r["project"]]["edges"] += len(edges_from(r["src_py_files"]))
    s["per_project"] = perproj
    return s, edges

raw_sum, raw_edges = summarize(records, "raw", untangle=False)
unt_sum, unt_edges = summarize(records, "untangled", untangle=True)

with open(os.path.join(OUT, f"p1_records_{STAMP}.json"), "w", encoding="utf-8") as f:
    json.dump(records, f, indent=1)
with open(os.path.join(OUT, f"p1_edges_raw_{STAMP}.json"), "w", encoding="utf-8") as f:
    json.dump(raw_edges, f, indent=1)
with open(os.path.join(OUT, f"p1_edges_untangled_{STAMP}.json"), "w", encoding="utf-8") as f:
    json.dump(unt_edges, f, indent=1)
with open(os.path.join(OUT, f"p1_summary_{STAMP}.json"), "w", encoding="utf-8") as f:
    json.dump({"raw": raw_sum, "untangled": unt_sum}, f, indent=1)

log("\n=== RAW ===")
for k in ["n_bugs_total","n_patch_ok","n_bugs_with_src_py","n_multifile_src_bugs","n_cochange_edges"]:
    log(f"  {k}: {raw_sum[k]}")
log("  src_py_fanout_hist:", raw_sum["src_py_fanout_hist"])
log("=== UNTANGLED (drop bugs touching >%d src .py) ===" % UNTANGLE_MAX_SRC)
for k in ["n_multifile_src_bugs","n_cochange_edges"]:
    log(f"  {k}: {unt_sum[k]}")
log("[done] outputs in", OUT)
LOG.close()
